spring:
  cloud:
    gateway:
        routes:
        - id: products
          uri: lb://products
          predicates:
          - Path=/api/products/**
          filters:
          - PrefixPath=/api/products
          - StripPrefix=2          
        - id: items
          uri: lb://items
          predicates:
          - Path=/api/items/**
          filters:
          - StripPrefix=2